# project ML
# it has 2 workflows - training and inference
project: ML
workflows:
  # training workflow
  # it has 4 steps - a, b, c and d
  # it is scheduled to run every 5 minutes
  - name: training
    steps:
      # step a executes the function step_fn in module located at ./src/training/a.py
      # it has no dependencies and returns 2 outputs -> x1, x2
      - name: a
        module: src.training.a
        function: step_fn
        dependencies: null
        return:
          - x1
          - x2
      # step b executes the function step_fn in module located at ./src/training/b.py
      # it has no dependencies and returns no outputs
      - name: b
        module: src.training.b
        function: step_fn
        dependencies: null
        return: null
      # step c executes the function step_fn in module located at ./src/training/c.py
      # it has 3 dependencies, 2 parameter-based (x1 and x2) and 1 order-based.
      # parameter x1 is sourced from output parameter x1 of step a
      # parameter x2 is sourced from output parameter x2 of step a
      # the third dependency is order-based i.e. it depends on the completion of step b
      # it returns 2 outputs -> x4 and x5
      - name: c
        module: src.training.c
        function: step_fn
        dependencies:
          - type: param
            name: x1
            source:
              step: a
              param: x1
          - type: param
            name: x2
            source:
              step: a
              param: x2
          - type: order
            name: start
            source:
              step:
                - b
        return:
          - x4
          - x5
      # step d executes the function step_fn in module located at ./src/training/d.py
      # it has 1 parameter-based dependency (x5) which is sourced from output parameter x4 of step c
      # parameter x5 is sourced from output parameter x4 of step c
      # the third dependency is order-based i.e. it depends on the completion of step b
      # it returns 1 output -> x6
      - name: d
        module: src.training.d
        function: step_fn
        dependencies:
          - type: param
            name: x5
            source:
              step: c
              param: x4
        return:
          - x6
    schedule: "*/5 * * * *"

  # inference workflow
  # it has 3 steps - a, b and c
  # it is scheduled to run every 20 minutes
  - name: inference
    steps:
      - name: a
        module: src.inference.a
        function: step_fn
        dependencies: null
        return:
          - x1
          - x2
      - name: b
        module: src.inference.b
        function: step_fn
        dependencies: null
        return: null
      - name: c
        module: src.inference.c
        function: step_fn
        dependencies:
          - type: param
            name: x1
            source:
              step: a
              param: x1
          - type: param
            name: x2
            source:
              step: a
              param: x2
          - type: order
            name: start
            source:
              step:
                - b
        return:
          - x4
          - x5
    schedule: "*/20 * * * *"
